#!/bin/bash

#set -x

PATH=/usr/sbin:/usr/bin:/sbin:/bin
DRAWIO_USER=drawio

# do we need to use sudo to start docker containers?
( id -Gn | grep -q docker ) || SUDO=sudo

USER_UID=$(id -u)
USER_GID=$(id -g)

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

DOWNLOAD_DIR=$(xdg-user-dir DOWNLOAD)
if [ -z "${DOWNLOAD_DIR}" ]; then
    DOWNLOAD_DIR="${HOME}/Downloads"
fi;
DOCUMENTS_DIR=$(xdg-user-dir DOCUMENTS)
if [ -z "${DOCUMENTS_DIR}" ]; then
    DOCUMENTS_DIR="${HOME}/Documents"
fi;

list_commands() {
  echo ""
  echo "Launch drawio using:"
#  echo "  drawio                        OR "
  echo "  drawio-wrapper bash"
  echo ""
  exit 1
}

cleanup_stopped_drawio_instances(){
  echo "Cleaning up stopped drawio instances..."
  for c in $(${SUDO} docker ps -a -q)
  do
    image="$(${SUDO} docker inspect -f {{.Config.Image}} ${c})"
    if [ "${image}" == "olberger/docker-drawio-desktop-linux:latest" ]; then
      running=$(${SUDO} docker inspect -f {{.State.Running}} ${c})
      if [ "${running}" != "true" ]; then
        ${SUDO} docker rm "${c}" >/dev/null
      fi
    fi
  done
}

prepare_docker_env_parameters() {
  ENV_VARS+=" --env=USER_UID=${USER_UID}"
  ENV_VARS+=" --env=USER_GID=${USER_GID}"
  ENV_VARS+=" --env=DISPLAY=unix$DISPLAY"
  ENV_VARS+=" --env=XAUTHORITY=${XAUTH}"
  ENV_VARS+=" --env=TZ=$(date +%Z)"
}

prepare_docker_volume_parameters() {
  touch ${XAUTH}
  xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -

  if [[ -z "${DRAWIO_HOME}" ]]; then
      DRAWIO_HOME=${HOME} # Default directory
      CURDIR=`pwd`
  else
      CURDIR=${DRAWIO_HOME}
    DOWNLOAD_DIR=${DOWNLOAD_DIR/$HOME/$DRAWIO_HOME}
    DOCUMENTS_DIR=${DOCUMENTS_DIR/$HOME/$DRAWIO_HOME}
    mkdir -p {$DOWNLOAD_DIR,$DOCUMENTS_DIR}

#    mkdir -p ${DRAWIO_HOME}/{.config,.cache}
    mkdir -p ${DRAWIO_HOME}/.config
  fi
  mkdir -p ${CURDIR}/diagrams-from-host
  
  echo "Using DRAWIO_HOME: ${DRAWIO_HOME}"

#  touch ${DRAWIO_HOME}/.config/zoomus.conf # create if not exists

  -v $CURDIR:/
  VOLUMES+=" --volume=${CURDIR}/diagrams-from-host:/home/${DRAWIO_USER}/diagrams-from-host"
#  VOLUMES+=" --volume=${DRAWIO_HOME}/.config/zoomus.conf:/home/${DRAWIO_USER}/.config/zoomus.conf"
  VOLUMES+=" --volume=${DRAWIO_HOME}/.config/draw.io:/home/${DRAWIO_USER}/.config/draw.io"
  #VOLUMES+=" --volume=${DRAWIO_HOME}/.config/Microsoft:/home/${DRAWIO_USER}/.config/Microsoft"
  # VOLUMES+=" --volume=${DRAWIO_HOME}/.cache/zoom:/home/${DRAWIO_USER}/.cache/zoom"
  # VOLUMES+=" --volume=${DRAWIO_HOME}/.zoom:/home/${DRAWIO_USER}/.zoom"
  # VOLUMES+=" --volume=${DOWNLOAD_DIR}:/home/${DRAWIO_USER}/Downloads"
  # VOLUMES+=" --volume=${DOCUMENTS_DIR}:/home/${DRAWIO_USER}/Documents"
  VOLUMES+=" --volume=${XSOCK}:${XSOCK}"
  VOLUMES+=" --volume=${XAUTH}:${XAUTH}"
#  VOLUMES+=" --volume=/run/user/${USER_UID}/pulse:/run/pulse"
}

prepare_docker_device_parameters() {
  # enumerate video devices for webcam support
  VIDEO_DEVICES=
  for device in /dev/video*
  do
    if [ -c $device ]; then
      VIDEO_DEVICES="${VIDEO_DEVICES} --device $device:$device"
    fi
  done
}

prog=$(basename $0)
exec=$(which $prog)

if [[ ${prog} == "drawio-wrapper" ]]; then
  case ${1} in
    # drawio)
    #   prog=${1}
    #   shift
    #   ;;
    bash)
      prog=${1}
      shift
      ;;
    *|help)
      list_commands
      exit 1
      ;;
  esac
elif [[ -n ${exec} ]]; then
    # launch host binary if it exists
    exec ${exec} $@
fi

cleanup_stopped_drawio_instances
prepare_docker_env_parameters
prepare_docker_volume_parameters
#prepare_docker_device_parameters

echo "Starting ${prog}..."
#${SUDO} docker run -d \
  # ${VIDEO_DEVICES} \
  # --device /dev/dri \
${SUDO} docker run -it \
  --privileged \
  ${ENV_VARS} \
  ${VOLUMES} \
  ${DRAWIO_EXTRA_DOCKER_ARGUMENTS} \
  --name drawio \
  olberger/docker-drawio-desktop-linux:latest ${prog} $@

#>/dev/null
